Updated the pipeline

diff --git a/.github/workflows/stellar-ci.yml b/.github/workflows/stellar-ci.yml
--- a/.github/workflows/stellar-ci.yml
+++ b/.github/workflows/stellar-ci.yml
@@ -3,9 +3,8 @@ name: Dev-ops-assignnment-api-pipeline
 on:
   push:
     branches:
-      - main
-      - staging
-
+      [main, staging, test]
+      
 jobs:
   deploy:
     name: test, build & push image to docker hub
@@ -52,8 +51,8 @@ jobs:
         push: true
         tags: ${{ secrets.DOCKER_USERNAME }}/fastapi:latest
 
-    # Step 7: SSH into the Azure VM and deploy Docker container in ssh -i use your own path/to/key.pem
-    - name: Deploy to Azure VM
+    # Step 7 Setup SSH key to connect to the Azure VM
+     - name: Setup SSH key and add it to known hosts
       run: |
         echo "${{ secrets.AZURE_SSH_KEY }}" > /tmp/key.pem
         ls /tmp
@@ -61,38 +60,47 @@ jobs:
         mkdir -p ~/.ssh
         touch ~/.ssh/known_hosts  # Create the known_hosts file if it doesn't exist
         ssh-keyscan ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts
+
+    # Step 8: SSH into the Azure VM and deploy Docker container in ssh -i use your own path/to/key.pem
+    - name: Deploy to Azure VM
+      run: |
+        # echo "${{ secrets.AZURE_SSH_KEY }}" > /tmp/key.pem
+        # ls /tmp
+        # chmod 600 /tmp/key.pem
+        # mkdir -p ~/.ssh
+        # touch ~/.ssh/known_hosts  # Create the known_hosts file if it doesn't exist
+        # ssh-keyscan ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts
+        echo "> Deploying fastapi application..."
         ssh -T -i /tmp/key.pem ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
-          pwd
-          ls -l
           docker compose -f ./dev-ops-assignment-api/docker-compose.yml pull
-          docker compose -f ./dev-ops-assignment-api/docker-compose.yml down # && \
-          # docker rm fastapi-container
+          docker compose -f ./dev-ops-assignment-api/docker-compose.yml down 
           docker compose -f ./dev-ops-assignment-api/docker-compose.yml up -d
+          echo "> fastapi application deployed sucessfully"
         EOF
 
-    - name: Execute health check and Rollback if health check fails
-      run: |
-        curl http://google.com
-        curl 20.123.62.2:8000 -m 5
-        curl 20.123.62.2:8000/health -m 5
+    # - name: Execute health check and Rollback if health check fails
+    #   run: |
+    #     curl http://google.com
+    #     curl 20.123.62.2:8000 -m 5
+    #     curl 20.123.62.2:8000/health -m 5
 
-    # Step 8: Execute the healthcheck through a curl command to the /health endpoint. If it returns non zero, rollback to the stable verson
-    - name: Execute health check and Rollback if health check fails
-      run: |
-        echo "${{ secrets.AZURE_SSH_KEY }}" > /tmp/key.pem
-        chmod 600 /tmp/key.pem
-        mkdir -p ~/.ssh
-        touch ~/.ssh/known_hosts
-        ssh-keyscan ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts
-        ssh -T -i /tmp/key.pem ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
-          if ! curl -f http://localhost:8000/health; then
-            echo "Health check failed. Rolling back to stable version."
-            # Modify the docker-compose.yml to switch to the stable image for FastAPI
-            sed -i 's/image: ${{ secrets.DOCKER_USERNAME }}\/fastapi:latest/image: ${{ secrets.DOCKER_USERNAME }}\/fastapi:stable/' ./dev-ops-assignment-api/docker-compose.yml
-            docker compose -f ./dev-ops-assignment-api/docker-compose.yml up -d fastapi  # Only restart FastAPI service with the stable image
-            echo "Rolling back complete. Stable version is running."
-            exit 1 # This is to make the pipeline fail after rollback to indicate to the developer that it failed
-          else
-            echo "Health check passed. Continuing the pipeline"
-          fi
-        EOF
+    # # Step 9: Execute the healthcheck through a curl command to the /health endpoint. If it returns non zero, rollback to the stable verson
+    # - name: Execute health check and Rollback if health check fails
+    #   run: |
+    #     echo "${{ secrets.AZURE_SSH_KEY }}" > /tmp/key.pem
+    #     chmod 600 /tmp/key.pem
+    #     mkdir -p ~/.ssh
+    #     touch ~/.ssh/known_hosts
+    #     ssh-keyscan ${{ secrets.AZURE_VM_IP }} >> ~/.ssh/known_hosts
+    #     ssh -T -i /tmp/key.pem ${{ secrets.AZURE_USERNAME }}@${{ secrets.AZURE_VM_IP }} << 'EOF'
+    #       if ! curl -f http://localhost:8000/health; then
+    #         echo "Health check failed. Rolling back to stable version."
+    #         # Modify the docker-compose.yml to switch to the stable image for FastAPI
+    #         sed -i 's/image: ${{ secrets.DOCKER_USERNAME }}\/fastapi:latest/image: ${{ secrets.DOCKER_USERNAME }}\/fastapi:stable/' ./dev-ops-assignment-api/docker-compose.yml
+    #         docker compose -f ./dev-ops-assignment-api/docker-compose.yml up -d fastapi  # Only restart FastAPI service with the stable image
+    #         echo "Rolling back complete. Stable version is running."
+    #         exit 1 # This is to make the pipeline fail after rollback to indicate to the developer that it failed
+    #       else
+    #         echo "Health check passed. Continuing the pipeline"
+    #       fi
+    #     EOF
